-- AlterTable
ALTER TABLE "users" ALTER COLUMN "email" SET DATA TYPE VARCHAR(500);

-- AlterTable
ALTER TABLE "whitelabel" ALTER COLUMN "name" SET DATA TYPE VARCHAR(500),
ALTER COLUMN "url" SET DATA TYPE VARCHAR(500);
